### PR TITLE
[internal] Create hybrid method to strip special chars unless only di…

### PR DESCRIPTION
**Pull request by NiceMLT**
A third way that combines 7 and 8's logic.  I *think* I like this one best.

### CODE REVIEW

**Comment by NiceMLT** [comment]
@drewblas I thought about that.  Either way, I'm sure I can subclass it and make it cleaner if we want.  But I had a couple of thoughts on it after spending the last couple of days implementing it within the gem and working within our app:

1) Are we sure that allowing people to "opt in/out" is best?  The requirement to clean those characters isn't going to ever go away so at some point we're going to have to tell clients that we don't support it anymore (or we'll have to keep letting them "opt out" in the future.  In the meantime it means extra logic for every export and another setting to maintain.  I know that's not a "lot" in terms of DB/app strain but it's not nothing and it also means supporting 2x tests for every export we do as well.  The more I thought about it the more it feels like we should just change the library and give people ample notice.    Is the biggest issue here the Pen Testers and not feeling like we have time for proper rollout/messaging? 

2) Sort of related to 1. I wrote everything with the sanitized version of the data as the default since that's (hopefully/ideally/prospectively) what clients should be using.  Defaulting to false to me just feels like kicking the can down the road and then later on when we really really want everyone to be using the sanitizer, we'll have to come back in and do more work then.  It felt more "right" now to just go ahead and sanitize as the standard and (if) we let people opt-out then we can catch that and control it.   

But honestly to me it feels best/cleanest/most right.  We'd be protecting clients from themselves a little and truly satisfying the testers at the cost of maybe having to contact some of our clients and updating the documentation (which we will have to do anyway and at least with a clean change, we can create really clean documentation).    I didn't arrive at this lightly, fwiw.  I've got a bunch of the work done locally to pass in the additional argument everywhere we are calling the `comma` library and am working on creating another round of specs for all of them.

**Comment by drewblas** [comment]
I agree with your overall assertions.  And I think we are of the same mind on the long-term objective.  But what I'm advocating for is making small, incremental changes for a number of significant reasons (some of which you mentioned obliquely) but I'll try to be clearer:

*  Every business uses something like the API or CSV in different ways we haven't anticipated.  
*  Our desire to change at any speed does not translate to being able to force our customers to do anything.  They rely on us to run their business and they expect that what works today will continue to work tomorrow.  
* That translates practically to mean that any type of breaking change like this has to follow a clear 
sequence of steps:

1.  We notify them and provide a deadline
2.  But our definition of "ample" notice and what a merchant will actually ACCEPT are very different things.  No amount of notice will get everyone to fix their integration in time.  
3.  We provide the ability to customize on an account-by-account basis whether the change is in-effect or not.  
4.  Some will want to switch earlier
5.  Some to test and then switch back
6.  And some we must allow those who can't meet the deadline to hold off until a later date
7.  There is NO permanent opt out.  Everyone will be forced to switch at some future point.  But that happens when we are confident that each customer is aware and ready for the change and can _continue to operate their business in the meantime_.  Merchants leave _very fast_ if their business suddenly stops working because of a change we made, no matter how much notice we gave them.

So that's the philosophical part.  We've done enough of these types of changes to understand how it will play out if we don't provide this dynamic ramp ability.

So on "how do we implement given these constraints", I'm simply advocating for:

1.  Avoid jumping to the end.  I agree with your ideas about where we want to BE at the end of the process:   Single class, default is to sanitize, everyone is switched, one code path.
2.  But GETTING there requires an incremental approach.  
3.  Start with a minimal change, that can be rolled out dynamically and backed out at any time.
4.  Continue to default to the "old behavior" until the new behavior is established before switching
5.  Clean as you go.  It's a long process and the intermediate code has to live for a long time, so it should be as clean as it can be (but wanting the "cleanest" code is not a justification to circumvent to incremental/phased-rollout requirements)

I'm understanding that it is WAY more work in the interim.  Jumping to the end and ignoring compatibility is always going to be easier and faster.  It just simply isn't an option.

On your question on the pen testers:  Yes, getting this in front of them is important.  But it is not the driving concern.   We take the incremental approach for the merchants.  It just so happens that providing dynamic rollout and backwards compatibility ALSO helps us deliver to the pen testers faster than having to wait for the full merchant rollout to complete.

**Comment by NiceMLT** [comment]
@drewblas Thanks for the clarification/explanation.  I hope I didn't imply you hadn't thought it through.  I'm on it.

**Comment by drewblas** [comment]
Quite the contrary!  It's clear you thought about it deeply!

**Comment by NiceMLT** [comment]
moving notes out of this

**Comment by NiceMLT** [comment]
closing in favor of https://github.com/chargify/comma/pull/10 (which is basically the same but clealer)

**Pull request closed without merging**
